name: CI
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: NPM Install
        run: npm install

      - name: Run tests
        run: npm run build-debug && npm run test
